import type { GuestHouseType } from "@/types/guest-room.type";

export const dummyGuestHouses: GuestHouseType[] = [
  {
    id: "1",
    name: "Sunset Guest House",
    images: [
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Balcony overlooking the ocean",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Modern lounge area",
      },
    ],
    about: {
      description:
        "A cozy seaside retreat offering modern rooms with stunning views, local cuisine, and warm hospitality. Perfect for beach lovers and honeymooners.",
      review: {
        averageRating: 4.7,
        totalReviewers: 230,
      },
    },
    feedback: [
      { message: "Best sea view in Addis!", rating: 5 },
      { message: "Staff were friendly, breakfast was delicious.", rating: 4 },
    ],
    address: "123 Beach Road, Addis Ababa",
    location: {
      continent: "Africa",
      country: "Ethiopia",
      city: "Addis Ababa",
      subcity: "Bole",
      nearby: "Friendship Park",
    },
    facilities: [
      "Free Wi-Fi",
      "Sea view",
      "Breakfast included",
      "Airport Shuttle",
    ],
    contact: { phone: "+251-912345678", email: "sunset@guest.com" },

    rooms: [
      {
        id: "1",
        name: "Sunset Single",
        roomId: "R-1001",
        type: "SINGLE",
        price: "55",
        description: "Compact room with a balcony facing the ocean.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Cozy single bed setup",
          },
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Cozy single bed setup",
          },
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Cozy single bed setup",
          },
        ],
        availability: true,
        guestHouseId: "1",
        occupiedById: null,
        square_meters: 18,
        max_occupancy: 1,
        beds: {
          single_beds: 1,
          double_beds: 0,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: true,
          bathtub: false,
          shower: true,
          hairdryer: true,
          minibar: false,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: false,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: false },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: false,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
      {
        id: "2",
        name: "Sunset Deluxe Double",
        roomId: "R-1002",
        type: "DELUXE",
        price: "120",
        description: "Spacious deluxe double room with balcony and sea view.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Deluxe double room interior",
          },
        ],
        availability: false,
        guestHouseId: "1",
        occupiedById: null,
        square_meters: 35,
        max_occupancy: 3,
        beds: {
          single_beds: 0,
          double_beds: 1,
          queen_beds: 1,
          king_beds: 0,
          sofa_beds: 0,
          cribs: true,
        },
        living_features: {
          private_bathroom: true,
          bathtub: true,
          shower: true,
          hairdryer: true,
          minibar: true,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: true },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: true,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
    ],
  },

  {
    id: "3",
    name: "Highland Lodge",
    images: [
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Mountain view from lodge",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Rustic wooden cabin",
      },
    ],
    about: {
      description:
        "Nestled in the highlands, this lodge offers a peaceful retreat with panoramic mountain views, fireplaces, and authentic Ethiopian hospitality.",
      review: {
        averageRating: 4.3,
        totalReviewers: 98,
      },
    },
    feedback: [
      { message: "Loved the fresh mountain air!", rating: 5 },
      { message: "Cozy, but Wi-Fi was a bit weak.", rating: 3 },
    ],
    address: "456 Hilltop, Addis Ababa",
    location: {
      continent: "Africa",
      country: "Ethiopia",
      city: "Addis Ababa",
      subcity: "Yeka",
      nearby: "Entoto Park",
    },
    facilities: ["Free Wi-Fi", "Fireplace", "Mountain View", "Restaurant"],
    contact: { phone: "+251-934567890", email: "highland@guest.com" },
    rooms: [
      {
        id: "1",
        name: "Highland Single",
        roomId: "R-2001",
        type: "SINGLE",
        price: "70",
        description: "Single room with warm wooden design and mountain views.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Single wooden cabin",
          },
        ],
        availability: true,
        guestHouseId: "2",
        occupiedById: null,
        square_meters: 20,
        max_occupancy: 1,
        beds: {
          single_beds: 1,
          double_beds: 0,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: true,
          bathtub: false,
          shower: true,
          hairdryer: false,
          minibar: false,
          tv: true,
          streaming_tv: false,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: false,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: false },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: false,
          digital_keys: false,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
      {
        id: "2",
        name: "Highland Suite",
        roomId: "R-2002",
        type: "SUITE",
        price: "200",
        description:
          "Spacious suite with fireplace, balcony, and breathtaking views.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Suite interior with fireplace",
          },
        ],
        availability: false,
        guestHouseId: "2",
        occupiedById: null,
        square_meters: 50,
        max_occupancy: 4,
        beds: {
          single_beds: 0,
          double_beds: 0,
          queen_beds: 1,
          king_beds: 1,
          sofa_beds: 1,
          cribs: true,
        },
        living_features: {
          private_bathroom: true,
          bathtub: true,
          shower: true,
          hairdryer: true,
          minibar: true,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: true,
        },
        accessibility: { wheelchair_accessible: true },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: true,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
    ],
  },

  {
    id: "2",
    name: "Highland Lodge",
    images: [
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Mountain view from lodge",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Rustic wooden cabin",
      },
    ],
    about: {
      description:
        "Nestled in the highlands, this lodge offers a peaceful retreat with panoramic mountain views, fireplaces, and authentic Ethiopian hospitality.",
      review: {
        averageRating: 4.3,
        totalReviewers: 98,
      },
    },
    feedback: [
      { message: "Loved the fresh mountain air!", rating: 5 },
      { message: "Cozy, but Wi-Fi was a bit weak.", rating: 3 },
    ],
    address: "456 Hilltop, Addis Ababa",
    location: {
      continent: "Africa",
      country: "Ethiopia",
      city: "Addis Ababa",
      subcity: "Yeka",
      nearby: "Entoto Park",
    },
    facilities: ["Free Wi-Fi", "Fireplace", "Mountain View", "Restaurant"],
    contact: { phone: "+251-934567890", email: "highland@guest.com" },
    rooms: [
      {
        id: "1",
        name: "Highland Single",
        roomId: "R-2001",
        type: "SINGLE",
        price: "70",
        description: "Single room with warm wooden design and mountain views.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Single wooden cabin",
          },
        ],
        availability: true,
        guestHouseId: "2",
        occupiedById: null,
        square_meters: 20,
        max_occupancy: 1,
        beds: {
          single_beds: 1,
          double_beds: 0,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: true,
          bathtub: false,
          shower: true,
          hairdryer: false,
          minibar: false,
          tv: true,
          streaming_tv: false,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: false,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: false },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: false,
          digital_keys: false,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
      {
        id: "2",
        name: "Highland Suite",
        roomId: "R-2002",
        type: "SUITE",
        price: "200",
        description:
          "Spacious suite with fireplace, balcony, and breathtaking views.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Suite interior with fireplace",
          },
        ],
        availability: false,
        guestHouseId: "2",
        occupiedById: null,
        square_meters: 50,
        max_occupancy: 4,
        beds: {
          single_beds: 0,
          double_beds: 0,
          queen_beds: 1,
          king_beds: 1,
          sofa_beds: 1,
          cribs: true,
        },
        living_features: {
          private_bathroom: true,
          bathtub: true,
          shower: true,
          hairdryer: true,
          minibar: true,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: true,
        },
        accessibility: { wheelchair_accessible: true },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: true,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
    ],
  },
  {
    id: "4",
    name: "Highland Lodge",
    images: [
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Mountain view from lodge",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Rustic wooden cabin",
      },
    ],
    about: {
      description:
        "Nestled in the highlands, this lodge offers a peaceful retreat with panoramic mountain views, fireplaces, and authentic Ethiopian hospitality.",
      review: {
        averageRating: 4.3,
        totalReviewers: 98,
      },
    },
    feedback: [
      { message: "Loved the fresh mountain air!", rating: 5 },
      { message: "Cozy, but Wi-Fi was a bit weak.", rating: 3 },
    ],
    address: "456 Hilltop, Addis Ababa",
    location: {
      continent: "Africa",
      country: "Ethiopia",
      city: "Addis Ababa",
      subcity: "Yeka",
      nearby: "Entoto Park",
    },
    facilities: ["Free Wi-Fi", "Fireplace", "Mountain View", "Restaurant"],
    contact: { phone: "+251-934567890", email: "highland@guest.com" },
    rooms: [
      {
        id: "1",
        name: "Highland Single",
        roomId: "R-2001",
        type: "SINGLE",
        price: "70",
        description: "Single room with warm wooden design and mountain views.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Single wooden cabin",
          },
        ],
        availability: true,
        guestHouseId: "2",
        occupiedById: null,
        square_meters: 20,
        max_occupancy: 1,
        beds: {
          single_beds: 1,
          double_beds: 0,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: true,
          bathtub: false,
          shower: true,
          hairdryer: false,
          minibar: false,
          tv: true,
          streaming_tv: false,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: false,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: false },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: false,
          digital_keys: false,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
      {
        id: "2",
        name: "Highland Suite",
        roomId: "R-2002",
        type: "SUITE",
        price: "200",
        description:
          "Spacious suite with fireplace, balcony, and breathtaking views.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Suite interior with fireplace",
          },
        ],
        availability: false,
        guestHouseId: "2",
        occupiedById: null,
        square_meters: 50,
        max_occupancy: 4,
        beds: {
          single_beds: 0,
          double_beds: 0,
          queen_beds: 1,
          king_beds: 1,
          sofa_beds: 1,
          cribs: true,
        },
        living_features: {
          private_bathroom: true,
          bathtub: true,
          shower: true,
          hairdryer: true,
          minibar: true,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: true,
        },
        accessibility: { wheelchair_accessible: true },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: true,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
    ],
  },
  {
    id: "5",
    name: "Highland Lodge",
    images: [
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Mountain view from lodge",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
        name: "Rustic wooden cabin",
      },
    ],
    about: {
      description:
        "Nestled in the highlands, this lodge offers a peaceful retreat with panoramic mountain views, fireplaces, and authentic Ethiopian hospitality.",
      review: {
        averageRating: 4.3,
        totalReviewers: 98,
      },
    },
    feedback: [
      { message: "Loved the fresh mountain air!", rating: 5 },
      { message: "Cozy, but Wi-Fi was a bit weak.", rating: 3 },
    ],
    address: "456 Hilltop, Addis Ababa",
    location: {
      continent: "Africa",
      country: "Ethiopia",
      city: "Addis Ababa",
      subcity: "Yeka",
      nearby: "Entoto Park",
    },
    facilities: ["Free Wi-Fi", "Fireplace", "Mountain View", "Restaurant"],
    contact: { phone: "+251-934567890", email: "highland@guest.com" },
    rooms: [
      {
        id: "1",
        name: "Highland Single",
        roomId: "R-2001",
        type: "SINGLE",
        price: "70",
        description: "Single room with warm wooden design and mountain views.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Single wooden cabin",
          },
        ],
        availability: true,
        guestHouseId: "2",
        occupiedById: null,
        square_meters: 20,
        max_occupancy: 1,
        beds: {
          single_beds: 1,
          double_beds: 0,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: true,
          bathtub: false,
          shower: true,
          hairdryer: false,
          minibar: false,
          tv: true,
          streaming_tv: false,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: false,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: false },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: false,
          digital_keys: false,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
      {
        id: "2",
        name: "Highland Suite",
        roomId: "R-2002",
        type: "SUITE",
        price: "200",
        description:
          "Spacious suite with fireplace, balcony, and breathtaking views.",
        images: [
          {
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTyaMqv9T_mEcd6EU6TH5Lp3_AkRqZL6OibA&s",
            name: "Suite interior with fireplace",
          },
        ],
        availability: false,
        guestHouseId: "2",
        occupiedById: null,
        square_meters: 50,
        max_occupancy: 4,
        beds: {
          single_beds: 0,
          double_beds: 0,
          queen_beds: 1,
          king_beds: 1,
          sofa_beds: 1,
          cribs: true,
        },
        living_features: {
          private_bathroom: true,
          bathtub: true,
          shower: true,
          hairdryer: true,
          minibar: true,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: true,
        },
        accessibility: { wheelchair_accessible: true },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: true,
        },
        last_updated: "2025-08-29T12:00:00Z",
      },
    ],
  },
];
